name: Milos
favicon: null
layout_spectrum: 0.051711442647501826
typography_spectrum: 0.8247920195572078
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.28010933683253825
  lightness: 0.5994287305511534
  saturation: 0.3943282845430076
  rhythmicContrast: 0.5331314671784639
purpose: []
